<?php
/**
 * Fields included in the Captain Admin Options Page
 *
 * @package   Captain Admin
 * @author    Captain Theme <info@captaintheme.com>
 * @license   GPL-2.0+
 * @link      http://captaintheme.com
 * @copyright 2014 Captain Theme
 *
 */

if( function_exists( "register_field_group" ) )
{
	register_field_group(array (
		'id' => 'acf_plugin-options',
		'title' => 'Admin Options',
		'fields' => array (
			array (
				'key' => 'field_538010b44faa6',
				'label' => 'Refresh To See Changes',
				'name' => '',
				'type' => 'message',
				'message' => '<strong>Please note that after saving your new settings, please <a href="admin.php?page=acf-options-cadmin">reload the page</a> or refresh (ctrl + R or command + R) to see your changes.</strong>',
			),
			array (
				'key' => 'field_538000bb5d5be',
				'label' => 'Branding',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_537fff1dea41e',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => 'Try to make it a .png with a transparent background.',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5381e9ed56d94',
				'label' => 'Logo Width',
				'name' => 'logo_width',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => 0,
			),
			array (
				'key' => 'field_5381ea3756d95',
				'label' => 'Logo Height',
				'name' => 'logo_height',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53858fe8c6c0b',
				'label' => 'Admin Favicon',
				'name' => 'admin_favicon',
				'type' => 'image',
				'instructions' => 'Upload a favicon here to be displayed on pages in the WordPress Admin. It should be a 16x16 or 32x32 image.',
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_53801e627faf8',
				'label' => 'Footer Text',
				'name' => 'footer_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538561f3da5e2',
				'label' => 'Change Options Page Name',
				'name' => 'change_options_page_name',
				'type' => 'text',
				'instructions' => 'This will change the name of this page displayed at the top.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5380088b1f049',
				'label' => 'Hide Stuff',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5f8eae53213a10c',
				'label' => 'Who do you want to hide everything for?',
				'name' => 'hide_for_choose_role',
				'type' => 'select',
				'instructions' => 'You can choose who all of the following options will be hidden for. So if you still want to see updates, Plugins etc., but don\'t want a client with a non-Adminstrator role to see it, you can choose to hide it just from them.',
				'choices' => array (
					'hide_all' => 'Hide From Everyone',
					'hide_non_admin' => 'Hide From Non-Administrators',
				),
				'default_value' => 'hide_all',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_538008921f04a',
				'label' => 'Hide WordPress Header Logo',
				'name' => 'hide_wordpress_header_logo',
				'type' => 'true_false',
				'instructions' => 'If selected this will hide the small WordPress logo/link in the top left corner of the admin.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5381d57a0f803',
				'label' => 'Hide WordPress Footer Version',
				'name' => 'hide_wordpress_footer_version',
				'type' => 'true_false',
				'instructions' => 'This will hide the text about WordPress and the version number in the bottom right footer.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5321d54a23f803',
				'label' => 'Hide WordPress Update Notice',
				'name' => 'hide_wordpress_update_notice',
				'type' => 'true_false',
				'instructions' => 'This will stop WordPress displaying notices about updating your WordPress Installation to the latest version.',
				'message' => '',
				'default_value' => 0,
			),

			// Make cleaner with a simple checkbox metafield in 1.2
			array (
				'key' => 'field_538560e205e66',
				'label' => 'Hide Posts',
				'name' => 'hide_posts',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
				'layout' => 'horizontal'
			),
			array (
				'key' => 'field_538560b305e63',
				'label' => 'Hide Media',
				'name' => 'hide_media',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538560c405e64',
				'label' => 'Hide Pages',
				'name' => 'hide_pages',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538560d605e65',
				'label' => 'Hide Comments',
				'name' => 'hide_comments',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385604c05e5e',
				'label' => 'Hide Appearance',
				'name' => 'hide_appearance',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385606905e5f',
				'label' => 'Hide Plugins',
				'name' => 'hide_plugins',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385608805e60',
				'label' => 'Hide Users',
				'name' => 'hide_users',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385609705e61',
				'label' => 'Hide Tools',
				'name' => 'hide_tools',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538560a105e62',
				'label' => 'Hide Settings',
				'name' => 'hide_settings',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538560f605e67',
				'label' => 'Hide Options Page',
				'name' => 'hide_options_page',
				'type' => 'true_false',
				'instructions' => 'WARNING: This will hide this page you\'re on now from being in the menu on the left. It will still be accessible at:
	<pre>http://yoursite.com/wp-admin/admin.php?page=acf-options-cadmin</pre>',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5383342251c19',
				'label' => 'Hide Screen Options Button',
				'name' => 'hide_screen_options_button',
				'type' => 'true_false',
				'instructions' => 'This will hide the button for Screen Options in the top right. It will not affect anything that is displayed - the button to bring down the screen options will simply not be there any more.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5383s261809c4',
				'label' => 'Hide Help Button',
				'name' => 'hide_help_button',
				'type' => 'true_false',
				'instructions' => 'This will hide the button for Help in the top right. It will not affect anything that is displayed - the button to bring down the additional help will simply not be there any more.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5325413zda3e2',
				'label' => 'Other',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53837454182y2',
				'label' => 'Add Post Thumbnails to Admin Post / Page Columns',
				'name' => 'add_thumbnails_columns',
				'type' => 'true_false',
				'instructions' => 'If enabled, a new column will be created in the Post/Page areas of the admin that will show each post/page\'s thumbnail/featured image.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52847302132g3',
				'label' => 'Remove WordPress Version & Current Theme From At A Glance Widget',
				'name' => 'remove_theme_right_now_widget',
				'type' => 'true_false',
				'instructions' => 'If enabled, the \'At A Glance\' Dashboard Widget will not display the WordPress version and current theme.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_52837354132p5',
				'label' => 'Hide Dashboard From Subscribers',
				'name' => 'hide_dashboard_subscribers',
				'type' => 'true_false',
				'instructions' => 'If enabled, users that are Subscribers will not have any access at all to the WordPress Dashboard.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53f0123b44oaa6',
				'label' => 'Admin Color Schemes',
				'name' => '',
				'type' => 'message',
				'message' => '<strong><a href="profile.php">Edit Your Admin Color Scheme</a></strong>',
			),
			array (
				'key' => 'field_538eaeed6381b',
				'label' => 'Default Admin Color Scheme',
				'name' => 'default_admin_color_scheme',
				'type' => 'select',
				'instructions' => 'This will be the default admin color scheme for new users. They will still be able to change it themselves unless you choose to prevent them in the next option.',
				'choices' => array (
					'Default' => 'Default',
					'Light' => 'Light',
					'80s-kid' => '80\'s Kid',
					'Aubergine' => 'Aubergine',
					'Blue' => 'Blue',
					'Coffee' => 'Coffee',
					'Cruise' => 'Cruise',
					'Ectoplasm' => 'Ectoplasm',
					'Flat' => 'Flat',
					'Lawn' => 'Lawn',
					'Midnight' => 'Midnight',
					'Ocean' => 'Ocean',
					'Primary' => 'Primary',
					'Seashore' => 'Seashore',
					'Sunrise' => 'Sunrise',
					'Vinyard' => 'Vinyard',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_538eb13e6381c',
				'label' => 'Stop Users From Choosing Admin Color Scheme',
				'name' => 'stop_users_from_choosing_admin_color_scheme',
				'type' => 'true_false',
				'instructions' => 'If selected, users will not have the ability to choose their color scheme (excluding Administrators).',
				'default_value' => 0,
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_53ha22523e6181b',
				'label' => 'Show Advanced Custom Fields Plugin (ACF)',
				'name' => 'show_acf_plugin',
				'type' => 'true_false',
				'instructions' => 'Captain Admin uses Advanced Custom Fields for some parts of the plugin. The fields area for the plugin has been hidden but if you would like to access it to use alongside Captain Admin, just check this option to do so.',
				'default_value' => 0,
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_538ea2ds2gd0ddd64df1',
				'label' => 'Custom Admin CSS',
				'name' => 'custom_admin_css',
				'type' => 'code_area',
				'language' => 'css',
				'theme' => 'monokai',
			),
			array (
				'key' => 'field_5385613cda5e0',
				'label' => 'Login Page',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5385614cda5e1',
				'label' => 'Custom Login Text',
				'name' => 'custom_login_text',
				'type' => 'textarea',
				'instructions' => 'Any text added here will be displayed on the login page (wp-login.php) above the login form.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5385014dda3e1',
				'label' => 'Custom Register Message',
				'name' => 'custom_register_message',
				'type' => 'textarea',
				'instructions' => 'Any text added here will be displayed on the register page (wp-login.php?action=register) below the email input in the form.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538563e119860',
				'label' => 'Logo Link',
				'name' => 'custom_login_link',
				'type' => 'text',
				'instructions' => 'This will change where the logo on the login page links to.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_523sg3ddg25fse2',
				'label' => 'Login Logo Title',
				'name' => 'custom_login_link_title',
				'type' => 'text',
				'instructions' => 'This will change the text that appears when you mouse over the login page logo.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53857402132b3',
				'label' => 'Enable Login By Email Address',
				'name' => 'enable_login_by_email_address',
				'type' => 'true_false',
				'instructions' => 'If enabled, users will be able to login with their email address <strong>or</strong> username. This is very useful as users tend to forget their usernames but they won\'t forget their email address!',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385743c132b4',
				'label' => 'Add \'Email\' to Login Form\'s Username Label',
				'name' => 'add_email_label_to_form',
				'type' => 'true_false',
				'instructions' => 'If you are allowing users to login with their email address, you may also want to change the login form\'s username label (the text above where they enter their username/email) so that it mentions Email. This option will allow you to do that. ',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53857402132b3',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_533563o119860',
				'label' => 'Custom Redirect After Login',
				'name' => 'custom_login_redirect',
				'type' => 'text',
				'instructions' => 'This will redirect all users to a custom page after logging in. Please enter a full valid URL. If left blank, the normal dashboard redirect will take place.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538523o119260',
				'label' => 'Change \'Register \' Text',
				'name' => 'register_text',
				'type' => 'text',
				'instructions' => 'Normally this link for users to sign up will say Register but you can change this here to anything you want, like Sign Up, etc.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534fsdfg8fa23f04a',
				'label' => 'Hide Forgot Password / Back to Blog Links',
				'name' => 'hide_login_pass_back',
				'type' => 'true_false',
				'instructions' => 'This will hide the Forgot Password and Back to Your Blog links underneath the login form (and also the register link if you allowed registration).',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_538fsdas38f21f04a',
				'label' => 'Hide Login Error Messages',
				'name' => 'hide_login_error_messages',
				'type' => 'true_false',
				'instructions' => 'You may not want WordPress to show errors when users try to log in and get their password/username wrong. Why? It can help hackers get into your account. If selected, all login error messages will be hidden and the error shake will stop.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53g2fsdasshsa38f21f04sda',
				'label' => 'Auto-Select Remember Me in Login Form',
				'name' => 'login_auto_remember_me',
				'type' => 'true_false',
				'instructions' => 'If selected, the Remember Me checkbox will automatically be selected in the login form for everyone.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5335hsaji231gdf860',
				'label' => 'Login Page Redirect',
				'name' => '',
				'type' => 'text',
				'instructions' => 'This will redirect the login page to a custom URL. Please enter a full valid URL. If left blank, no redirect will take place.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5381dcf8822e3',
				'label' => 'Background Image',
				'name' => 'background_image',
				'type' => 'radio',
				'choices' => array (
					'Waves' => 'Waves',
					'Wood' => 'Wood',
					'Forest' => 'Forest',
					'Leaf' => 'Leaf',
					'Rocks' => 'Rocks',
					'Custom' => 'Custom',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_5381bfe895f09',
				'label' => 'Custom Background Image',
				'name' => 'custom_background_image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5381dcf8822e3',
							'operator' => '==',
							'value' => 'Custom',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_538ed203dd64df1',
				'label' => 'Custom Login CSS',
				'name' => 'custom_login_css',
				'type' => 'code_area',
				'language' => 'css',
				'theme' => 'monokai',
			),
			array (
				'key' => 'field_5381e32fe92ba',
				'label' => 'Custom Widget',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5381e3c95e378',
				'label' => 'Enable Custom Widget #1',
				'name' => 'enable_custom_widget',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5381e3a05e377',
				'label' => 'Widget Title',
				'name' => 'widget_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5381e3c95e378',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5381e3f45e37a',
				'label' => 'Widget Content',
				'name' => 'widget_content',
				'type' => 'wysiwyg',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5381e3c95e378',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5341e3c95e328',
				'label' => 'Enable Custom Widget #2',
				'name' => 'enable_custom_widget_2',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5381easd05e377',
				'label' => 'Widget Title',
				'name' => 'widget_title_2',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5341e3c95e328',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538ads3f45e37a',
				'label' => 'Widget Content',
				'name' => 'widget_content_2',
				'type' => 'wysiwyg',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5341e3c95e328',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_53f153c95e328',
				'label' => 'Enable Custom Widget #3',
				'name' => 'enable_custom_widget_3',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5381asda05e377',
				'label' => 'Widget Title',
				'name' => 'widget_title_3',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53f153c95e328',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5381e3asdgfsd5e37a',
				'label' => 'Widget Content',
				'name' => 'widget_content_3',
				'type' => 'wysiwyg',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53f153c95e328',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5385697b5506f',
				'label' => 'Custom Admin Notice',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538569be55071',
				'label' => 'Enable Admin Notice',
				'name' => 'enable_admin_notice',
				'type' => 'true_false',
				'instructions' => 'If you choose to enable the admin notice, you will be able to enter in the contents of it below. This will appear throughout the entire WordPress admin so try to only put one there if it\'s important as it may become annoying over time (when that happens you can just disable it here again).',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5385698555070',
				'label' => 'Notice Text',
				'name' => 'notice_text',
				'type' => 'textarea',
				'instructions' => 'This is the text that will appear in your admin notice. No HTML Please.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538569be55071',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53856a8c55073',
				'label' => 'Notice Type',
				'name' => 'notice_type',
				'type' => 'radio',
				'instructions' => 'This allows you to choose which type of notice it is. A \'success\' one will be green while a \'warning\' one will be red.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538569be55071',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'updated' => 'Success',
					'error' => 'Warning',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'updated',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-cadmin',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
